### ISSUE TITLE
Pins not connected

### ISSUE THREAD

**Issue by charlesUnixPro** [Meisaka/CenMiniCom#2]
U37 pins A0, A1 are labeled "PL13", "PL14" but are not actually connected.

**Comment by Meisaka** [comment]
"U37" is not the style of identifier used in any of my schematics, nor did you specify a file (there's like 15+ different files).
Are you sure you are commenting on the correct project?

**Comment by charlesUnixPro** [comment]
Oops; yes,this belongs over on sjsoftware; apologies.

-- Charles
